###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "johnsmith",
    "name": "John Smith",
    "password": "hunter2"
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "johnsmith",
    "password": "hunter2"
}

###
# Should succeed has correct token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5zbWl0aCIsImlkIjoiNjNlZDQ3ZjU5NmMwMTZhYzRiNzQ3MjQwIiwiaWF0IjoxNjc2NDk1MDI4fQ.7z8W8PFRi6miE88uk3uqpfGQz3lO82LHHVf0p9R_Ew4

{
    "title": "My Day",
    "author": "John Smith",
    "url": "google.com",
    "likes": 3
}

###
# Delete with token
DELETE http://localhost:3003/api/blogs/63ed47a01773dac386dcec78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5zbWl0aCIsImlkIjoiNjNlZDJkZTUyOGIwMWMzOWRhMWUwODg3IiwiaWF0IjoxNjc2NDg4MTcwfQ.wgyJeTJuHKpRfWFHObfzXthHOvDerVBH0EgDbZbXcMs

###
# Delete no token
DELETE http://localhost:3003/api/blogs/63ed2df428b01c39da1e088c

###
GET http://localhost:3003/api/blogs/