GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/users/

###
DELETE http://localhost:3003/api/blogs/63e5467c76cbf69434224ac7

###
# Will succeed the first time
# And fail on subsequent requests
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My Day",
    "author": "John Smith",
    "url": "google.com",
    "likes": 3
}

###
# PUT request

PUT http://localhost:3003/api/blogs/63eac6b66fa16079050ead9d
Content-Type: application/json

{
    "title": "Cool Plants",
    "author": "Mike Greene",
    "url": "outlook.com",
    "likes": 8
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "johnsmith",
    "name": "John Smith",
    "password": "hunter2"
}