GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/users/

###
DELETE http://localhost:3003/api/blogs/63e5467c76cbf69434224ac7

###
# Fails - no token provided
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "My Day",
    "author": "John Smith",
    "url": "google.com",
    "likes": 3
}

###
# PUT request

PUT http://localhost:3003/api/blogs/63eac6b66fa16079050ead9d
Content-Type: application/json

{
    "title": "Cool Plants",
    "author": "Mike Greene",
    "url": "outlook.com",
    "likes": 8
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "johnsmith",
    "name": "John Smith",
    "password": "hunter2"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "johnsmith",
    "password": "hunter2"
}

###
# Should succeed has correct token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5zbWl0aCIsImlkIjoiNjNlZDJhNTU0NjA2MTllYTQ1NDQyYjRhIiwiaWF0IjoxNjc2NDg3MzY0fQ.PY7MBycjcfrd6q60icEqIrI8ZHqrZr7WOyc6SsB_obw

{
    "title": "My Day",
    "author": "John Smith",
    "url": "google.com",
    "likes": 3
}
